project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/fig/"
    - "slides/libs/"
    - "slides/partials/"
    - "slides/*_files/"
bibliography: files/bib/math60604.bib
csl: files/bib/apa.csl

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes


toc-title: "Table of content"
website:
  title: "Statistical modelling"
  site-url: "https://lbelzile.github.io/statmod"
  description: "The objective of this course is to provide students with the basics of statistical inference, as well as statistical tools for data modeling in a regression framework. The theory behind the statistical models will be reviewed with an emphasis on data applications in management."

  navbar:
    pinned: true
    background: "#002855"
    foreground: "#ffffff"
    right:
      - text: "Syllabus"
        file: "syllabus.qmd"
      - text: "Content"
        file: content/index.qmd
      - text: "Exercises"
        file: exercises/index.qmd
      - text: "Notes"
        href: "https://lbelzile.github.io/math60604a"
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      foreground: "#002855"
      contents:
        - text: "Ressources"
          file: content/index.qmd
        - text: "Installing **R**"
          file: content/installation.qmd
        - text: "Learning objectives"
          file: learningobjectives.qmd
        - section: "Pedagogical content"
          contents:
            - text: "Week 1"
              file: content/01-content.qmd
            - text: "Week 2"
              file: content/02-content.qmd
            - text: "Week 3"
              file: content/03-content.qmd
            - text: "Week 4"
              file: content/04-content.qmd
    - title: "Exercises"
      style: "docked"
      search: false
      foreground: "#002855"
      contents:
        - text: "Exercises"
          file: exercises/index.qmd 
        - section: "Hypothesis testing"
          contents:
            - text: "Exercise 1"
              file: exercises/01-exercise.qmd
            - text: "Solution 1"
              file: exercises/01-solution.qmd
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor1.name_no_title >}}]({{< var instructor1.url >}}), [{{< var instructor2.name_no_title >}}]({{< var instructor2.url >}})<br>
      Website template by [Dr. Andrew Heiss](https://www.andrewheiss.com/) under [MIT License](https://mit-license.org/)<br>
      Content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0 license](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

preview:
  port: 6200
  browser: true
  watch-inputs: true
  navigate: true

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
