---
title: "Linear models"
---

## Learning objectives

- list the assumptions of the linear model and understand their meaning;
- use graphical diagnostic tools to validate the model assumptions.
- interpret the coefficients of the log-linear model on a meaningful scale;
- conceptualize the notion of collinearity and understand its impacts on statistical inference.



## Content


- Course notes: chapter [4 (Linear regression models)](https://lbelzile.github.io/math60604a/linearmodels.html), Sections 4.7--4.8.


## In class

- [Slides](../slides/MATH60604A-slides6a.html) ([pdf](../slides/MATH60604A-slides6a.pdf) and [code](MATH60604A-slides6a.R))
- [Exercise on diagnostic plots](../exercises/graphical-diagnostics.qmd)


## After class 

- Watch the video of @sec-videos
- [Slides on colinearity](../slides/MATH60604A-slides6b.html) ([pdf](../slides/MATH60604A-slides6b.pdf) and [code](MATH60604A-slides6b.R))
- Exercises 2.4, 2.5, 2.9, 2.10



## Slides



<p class="text-center"><a class="btn btn-success btn-lg" target="_blank" href="../slides/MATH60604A-slides6a.html">{{< fa arrow-up-right-from-square >}} &ensp;View slides in new window</a> <a class="btn btn-success btn-lg" target="_blank" href="../slides/MATH60604A-slides6a.pdf" role="button">{{< fa file-pdf >}} &ensp;Download PDF of slides</a></p>

<div class="ratio ratio-16x9">
<iframe class="slide-deck" src="../slides/MATH60604A-slides6a.html"></iframe>
</div>



<p class="text-center"><a class="btn btn-success btn-lg" target="_blank" href="../slides/MATH60604A-slides6b.html">{{< fa arrow-up-right-from-square >}} &ensp;View slides in new window</a> <a class="btn btn-success btn-lg" target="_blank" href="../slides/MATH60604A-slides6b.pdf" role="button">{{< fa file-pdf >}} &ensp;Download PDF of slides</a></p>

<div class="ratio ratio-16x9">
<iframe class="slide-deck" src="../slides/MATH60604A-slides6b.html"></iframe>
</div>

## Videos {#sec-videos}

{{< video https://www.youtube.com/embed/JT61hD0HIvA >}}

